In [8]:
import numpy as np

## Question 1

In [11]:
def genMatrix(lis: list, size: int, is_increasing = False):
    if is_increasing:
        print(np.array([ j**i for j in lis for i in range(size)]).reshape(len(lis), size))
    else:
        print(np.array([ j** (size-1-i) for j in lis for i in range(size)]).reshape(len(lis), size))

In [16]:
lis = np.array([1,2,3])
size = 4
print("============")
print('DECREASING')
print("============")
genMatrix(lis, size)
print("============")
print('INCREASING')
print("============")
genMatrix(lis, size, is_increasing= True)

DECREASING
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]
INCREASING
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]


## Question 2

In [27]:
lis = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3

In [33]:
result = []
r_range = len(lis) - (window - 1)

for i in range(r_range):
    result.append(np.sum(lis[i:i+window])/window)
    
print(lis)

for i in len(result):
    printf(f"y{}")

In [34]:
result

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]